# Generated by Django 3.1.7 on 2021-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pollapp', '0003_choiceansw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
